### ISSUE TITLE
Unsure what inputs do

### ISSUE THREAD

**Issue by Spyromaniac31** [unknownskl/homebridge-smartglass#11] opened 2019-09-28 19:34 UTC
I just installed this plugin and have been able to power on and off my Xbox successfully. However, I can’t tell what the inputs (app, game, etc.) do.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by apexad** [comment] 2019-10-28 07:49
likely a duplicate of #3

**Comment by unknownskl** [comment] 2020-08-27 15:53
Correct. Closing issue.

**Closed by unknownskl** 2020-08-27 15:53 UTC
